name: read_tone_app
description: "독서 기록과 정리를 통한 효과적인 독서 관리 앱"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

# 주요 의존성
dependencies:
  flutter:
    sdk: flutter

  # UI 관련
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  fl_chart: ^1.1.0

  # 상태 관리
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1

  # 네트워크 및 데이터
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.3

  # 유틸리티
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.20.2
  logger: ^2.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  path_provider: ^2.1.4
  share_plus: ^11.1.0
  path: ^1.9.1
  uuid: ^4.5.1
  image_picker: ^1.2.0
  go_router: ^16.2.1
  flutter_dotenv: ^6.0.0

# 개발 의존성
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  riverpod_generator: ^2.4.3
  mockito: ^5.4.4
  mocktail: ^1.0.4

# 플러터 설정
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - .env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
