// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9QKhtszXhRYGdwzVmmxRlSdzVkbSpK_w',
    appId: '1:16057093480:web:2c09746446e0fdf318dadd',
    messagingSenderId: '16057093480',
    projectId: 'read-tone',
    authDomain: 'read-tone.firebaseapp.com',
    storageBucket: 'read-tone.firebasestorage.app',
    measurementId: 'G-JG8CR3DESW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3179SW_66q4eHN6WNcp6GDzfmw0RC414',
    appId: '1:16057093480:android:4f343f55513323be18dadd',
    messagingSenderId: '16057093480',
    projectId: 'read-tone',
    storageBucket: 'read-tone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHk9IjpMl4i-m7Gku_UO5SptXt8ix-82g',
    appId: '1:16057093480:ios:ed7804836edc5bc918dadd',
    messagingSenderId: '16057093480',
    projectId: 'read-tone',
    storageBucket: 'read-tone.firebasestorage.app',
    iosClientId:
        '16057093480-907bpgm82mcgf1e53dapmip3anc3o06d.apps.googleusercontent.com',
    iosBundleId: 'com.readtone.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHk9IjpMl4i-m7Gku_UO5SptXt8ix-82g',
    appId: '1:16057093480:ios:ed7804836edc5bc918dadd',
    messagingSenderId: '16057093480',
    projectId: 'read-tone',
    storageBucket: 'read-tone.firebasestorage.app',
    iosClientId:
        '16057093480-907bpgm82mcgf1e53dapmip3anc3o06d.apps.googleusercontent.com',
    iosBundleId: 'com.readtone.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9QKhtszXhRYGdwzVmmxRlSdzVkbSpK_w',
    appId: '1:16057093480:web:06cf36679029d76418dadd',
    messagingSenderId: '16057093480',
    projectId: 'read-tone',
    authDomain: 'read-tone.firebaseapp.com',
    storageBucket: 'read-tone.firebasestorage.app',
    measurementId: 'G-VDLEP9RFQ4',
  );
}
